# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WTLayerVisibilityCheck
                                 A QGIS plugin
 Set Layer Visibility Check depends on Data Sets
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-11
        copyright            : (C) 2020 by Alex Myltsev
        email                : alexmyltsev@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WTLayerVisibilityCheck class from file WTLayerVisibilityCheck.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wt_layer_visibility_check import WTLayerVisibilityCheck
    return WTLayerVisibilityCheck(iface)
